[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
dependsOn = ["setup"]
cmds = [
    "cd Sistema-Scouts-Jose-Hernandez",
    "chmod +x mvnw",
    "./mvnw clean package -DskipTests",
    "ls -la target/"
]

[start]
cmd = "cd Sistema-Scouts-Jose-Hernandez && java -jar target/Sistema-Scouts-Jose-Hernandez-*.jar"